blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Zcash Community Support
    url: https://forum.zcashcommunity.com/
    about: You're invited to ask questions about the ecosystem, community and Zebra
  - name: â“ General Questions about Zebra
    url: https://github.com/ZcashFoundation/zebra/discussions/categories/q-a
    about: Please ask and answer questions about Zebra as a discussion threads
