[builder.limits]
orchard_actions = 250

[consensus]
network = "regtest"
regtest_nuparams = [
    "5ba81b19:1",
    "76b809bb:1",
    "2bb40e60:1",
    "f5b9230b:1",
    "e9ff75a6:1",
    "c2d6d0b4:290",
    "c8e71055:291"
]

[database]
wallet = "data.sqlite"

[external]

[features]
as_of_version = "0.0.0"

[features.deprecated]

[features.experimental]

[indexer]
validator_address = "127.0.0.1:0"
validator_user = ".."
validator_password = ".."
db_path = "zaino"

[keystore]
encryption_identity = "identity.txt"

[note_management]

[rpc]
bind = ["127.0.0.1:0"]

[[rpc.auth]]
user = "zebra"
pwhash = "eaa27c81df81f655e69bbe84026e733a$bb9f70d53decfeca863cb114f7b0fd5ae050c7ef885c3d5fa73d5bace6c14fea"
